### ISSUE TITLE
Error after installing plugin

### ISSUE THREAD

**Issue by m41n** [k3nsei/ng-in-viewport#38]
I tried installing the plugin on a project I am working on and got the following errors when trying to build the project:

```
ERROR in PROJECT-DIRETORY/node_modules/ng-in-viewport/in-viewport/in-viewport.directive.d.ts (3,49): '=' expected.
ERROR in PROJECT-DIRETORY/node_modules/ng-in-viewport/in-viewport/in-viewport.directive.d.ts (3,42): Cannot find name 'unique'.
ERROR in PROJECT-DIRETORY/node_modules/ng-in-viewport/in-viewport/in-viewport.directive.d.ts (3,49): Cannot find name 'symbol'.
```

I checked the file inside node_modules which looks like this:
```

import { AfterViewInit, ElementRef, EventEmitter, OnDestroy } from '@angular/core';
import { InViewportService } from './in-viewport.service';
export declare const InViewportMetadata: unique symbol;
export declare class InViewportDirective implements AfterViewInit, OnDestroy {
    elementRef: ElementRef;
    private inViewportService;
    private config;
    action$: EventEmitter<any>;
    constructor(elementRef: ElementRef, inViewportService: InViewportService);
    updateConfig: any;
    ngAfterViewInit(): void;
    ngOnDestroy(): void;
    check(entry: IntersectionObserverEntry): void;
}
```

It seems there is a problem with the line:
`export declare const InViewportMetadata: unique symbol;`
especially the `unique symbol` part, it can't seem to handle it (as stated by the error messages posted above).
Am I missing something else? How can I get it working?
Thanks in advance

**Comment by k3nsei** [comment]
You need to update your typescript version.

wt., 15 maj 2018, 08:27 użytkownik m41n <notifications@github.com> napisał:

**Comment by k3nsei** [comment]
Hi, it look like you have older version of typescript. When you update it, then it should working.

**Comment by m41n** [comment]
thanks, will try that.

I also, just to be sure, tried to install the plugin again, adding @latest, now the error message does look like this:

```
ERROR in PROJECT-DIRECTORY/node_modules/ng-in-viewport/in-viewport/in-viewport.directive.d.ts (3,49): '=' expected.
ERROR in PROJECT-DIRECTORY/node_modules/ng-in-viewport/in-viewport/in-viewport.directive.d.ts (3,42): Cannot find name 'unique'.
ERROR in PROJECT-DIRECTORY/node_modules/ng-in-viewport/in-viewport/in-viewport.directive.d.ts (3,49): Cannot find name 'symbol'.
ERROR in Error: Metadata version mismatch for module PROJECT-DIRECTORY/node_modules/ng-in-viewport/index.d.ts, found version 4, expected 3, resolving symbol AppModule in PROJECT-DIRECTORY/src/app/app.module.ts, resolving symbol AppModule in PROJECT-DIRECTORY/src/app/app.module.ts, resolving symbol AppModule in PROJECT-DIRECTORY/src/app/app.module.ts
    at syntaxError (PROJECT-DIRECTORY\node_modules\@angular\compiler\bundles\compiler.umd.js:1729:34)
    at simplifyInContext (PROJECT-DIRECTORY\node_modules\@angular\compiler\bundles\compiler.umd.js:24979:23)
    at StaticReflector.simplify PROJECT-DIRECTORY\node_modules\@angular\compiler\bundles\compiler.umd.js:24991:13)
    at StaticReflector.annotations (PROJECT-DIRECTORY\node_modules\@angular\compiler\bundles\compiler.umd.js:24418:41)
    at _getNgModuleMetadata (PROJECT-DIRECTORY\node_modules\@angular\compiler-cli\src\ngtools_impl.js:138:31)
    at _extractLazyRoutesFromStaticModule (PROJECT-DIRECTORY\node_modules\@angular\compiler-cli\src\ngtools_impl.js:109:26)
    at Object.listLazyRoutesOfModule (PROJECT-DIRECTORY\node_modules\@angular\compiler-cli\src\ngtools_impl.js:53:22)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (PROJECT-DIRECTORY\node_modules\@angular\compiler-cli\src\ngtools_api.js:91:39)
    at AotPlugin._getLazyRoutesFromNgtools (PROJECT-DIRECTORY\node_modules\@ngtools\webpack\src\plugin.js:240:66)
    at _donePromise.Promise.resolve.then.then.then.then.then (PROJECT-DIRECTORY\node_modules\@ngtools\webpack\src\plugin.js:493:24)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```
I had that earlier, though it disappeared after adding everything required to my module.ts files.
Would this also be fixed by updating the typescript version?

**Comment by m41n** [comment]
sadly have to correct again, the second part of the error persits.
```
ERROR in Error: Metadata version mismatch for module PROJECT-DIRECTORY/node_modules/ng-in-viewport/index.d.ts, found version 4, expected 3, resolving symbol AppModule in PROJECT-DIRECTORY/src/app/app.module.ts, resolving symbol AppModule in PROJECT-DIRECTORY/src/app/app.module.ts, resolving symbol AppModule in PROJECT-DIRECTORY/src/app/app.module.ts
    at syntaxError (PROJECT-DIRECTORY\node_modules\@angular\compiler\bundles\compiler.umd.js:1729:34)
    at simplifyInContext (PROJECT-DIRECTORY\node_modules\@angular\compiler\bundles\compiler.umd.js:24979:23)
    at StaticReflector.simplify PROJECT-DIRECTORY\node_modules\@angular\compiler\bundles\compiler.umd.js:24991:13)
    at StaticReflector.annotations (PROJECT-DIRECTORY\node_modules\@angular\compiler\bundles\compiler.umd.js:24418:41)
    at _getNgModuleMetadata (PROJECT-DIRECTORY\node_modules\@angular\compiler-cli\src\ngtools_impl.js:138:31)
    at _extractLazyRoutesFromStaticModule (PROJECT-DIRECTORY\node_modules\@angular\compiler-cli\src\ngtools_impl.js:109:26)
    at Object.listLazyRoutesOfModule (PROJECT-DIRECTORY\node_modules\@angular\compiler-cli\src\ngtools_impl.js:53:22)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (PROJECT-DIRECTORY\node_modules\@angular\compiler-cli\src\ngtools_api.js:91:39)
    at AotPlugin._getLazyRoutesFromNgtools (PROJECT-DIRECTORY\node_modules\@ngtools\webpack\src\plugin.js:240:66)
    at _donePromise.Promise.resolve.then.then.then.then.then (PROJECT-DIRECTORY\node_modules\@ngtools\webpack\src\plugin.js:493:24)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```
